### ISSUE TITLE
Treat response type as JSON

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-browser-sdk#17]
When perfoming a request, the documentation recommand to do a `items = JSON.parse('' + res)` to get the JSONified result. As long as the expected result is always a JSON object, this post-treatment should be done by the SDK, not the app itself.

**Comment by flyingrub** [comment]
https://github.com/cozy/cozy-browser-sdk/commit/2686fe6ecf0883ef5e44c5510eb2e882220d7020 fixes it.
